#!/usr/bin/env ruby
# string_rearranger

# 20260924
# 0.0.0

def input_string
  ARGV[0]
end

def split_value
  ARGV[1]
end

def sliced_off_bit(input_string, slice_length)
  starting_point = split_value.to_i > 0 ? 0 : split_value.to_i
  input_string.split('')[starting_point, slice_length].join
  input_string[starting_point, slice_length]
end

def remainder_bit(input_string, slice_length)
  remainder_start = split_value.to_i > 0 ? slice_length.to_i : 0
  input_string[remainder_start, input_string.size - slice_length.to_i]
end

def rearrange_string(input_string, split_value)
  slice_length = split_value.to_i.abs
  if split_value.to_i > 0
    remainder_bit(input_string, slice_length) + sliced_off_bit(input_string, slice_length)
  else
    sliced_off_bit(input_string, slice_length) + remainder_bit(input_string, slice_length)
  end
end

def main(input_string, split_value)
  puts rearrange_string(input_string, split_value)
end

main(input_string, split_value)
